label thcynth1:
    hide screen hud
    "As you walk into the guild you see Cynthia and Thea talking."
    mc "{i}This can't be good. Better see what they're talking about."
    show worriedthop
    show normalcb
    c "Shhh... Shhh... He's here"
    hide worriedthop
    show worriedmc with easeinright
    show theshy
    c "Oh hey,[mc]."
    mc "H-Hey..."
    mc "{i}Oh my god... This was a bad idea."
    hide theshy
    show normalcb
    mc "Wh-what are you girls talking about."
    show theshy
    th "Nothing!"
    mc "{i}Thea looks off."
    show blushtalkac
    c "[mc] do you mind, we've got some buisness to attend to."
    hide normalcb
    hide blushtalkac with easeoutright
    hide theshy with easeoutright
    "Cynthia grabs Thea by her hand and drags her upto the guild quarters."
    mc "{i}There's something going on with those two."
    mc "......"
    mc "{i}Shit!"
    mc "{i}They're planning on murdering me."
    mc "{i}Yes, that's what this is."
    mc "{i}No... No... I'm over thinking this. They would never plan to kill me. Cynthia, maybe but Thea? No way."
    mc "{i}Everythings fine, [mc]."
    $ thcynthconfess += 1
    jump guild


label thcynth2:
hide screen hud
mc "Hmm... I wonder where Thea is, she should be working right now."
mc "Better ask July."
mc "Hey July, Did Thea come to work today?"
show adgc2
j "Yes, she did."
mc "I can't find her."
j "Hmm... Oh, she must be with Cynthia."
j "The two of them have been spending alot of time together recently."
mc "Are they in the guild quarters?"
j "Yes, is something the matter, [mc]?"
mc "Oh, no... No. It's nothing."
j "Oh, Okay."
scene adventurersguild_evening
mc "{i}The two of them are definietly plannig something."
mc "{i}I should try to figure out whats going on with thoses two."
"You go up to the guild quarters."
scene cynthroom with fade
show thinkmc with easeinright
mc "{i}They must be inside."
th "{i}Chatter... Chatter..."
c "{i}Chatter... Chatter... Chatter... Chatter..."
mc "{i}I can't hear them..."
c "We have to take him by suprise."
c "Did you get what I asked for?"
th "Y-yes."
c "And the rope?"
th "Here."
c "Good... Good."
th "Are you sure we need to tie him up?"
mc "{i}\"Tie him up?\""
c "Yes, We can't let him have his way."
c "This is a punishment afterall."
mc "{i}\"P-Punishment?\""
th "I guess you're right."
c "Hey Thea, if you don't feel like doing this it's totally fine to say so."
th "......"
th "No, it's alright."
th "It sounds... Fun."
mc "{i}Oh my god!"
c "Hoh-oh! and here I thought you were a pure angel... Hehe, very interesting."
th "Hehehe"
c "......"
c "You know Thea, I was thinking. Are you in-"
show smirksb
show suprised
sa "What's the sitch?"
mc "Aah!"
c "Huh? ...I think someone's at the door."
mc "-Sander!"
sa "I'm sorry."
mc "Come! We gotta go."
"The two of you run out of the guild quarters."
scene agblr with fade
show angry
show smirksb
mc "What the hell Sander!?"
show talkwasb
sa "Sorry, I didn't know you'd freak out like that."
mc "{i}Sigh"
sa "......"
sa "So?"
mc "So what?"
sa "You were spying on Cynthia. What did you hear?"
mc "I wasn't spying."
sa "You clearly were."
mc "Alright, I was spying on them."
sa "Them?"
mc "Yeah, Thea and Cynthia."
sa "The two of them were in there?"
mc "Yeah."
sa "Cynthia never lets anyone into her room- Well, except you, of course."
mc "Huh... me? I-I've never be-"
sa "Relax kid, I know the two of you have been fucking."
mc "wh-what- H-how did you know?"
sa "I have my ways."
"......"
"......"
mc "Did you peep on us?"
sa "No!"
show thinkmc
mc "......?"
sa "Anyway, what were the two of them talking about?"
mc "......"
menu:
        "Tell Sander.":
                mc "{i}...Sigh."
                show worriedmc
                mc "I think they're planning to kill me."
                sa "Kill you? Hahaha! Why would they want to do that?"
                mc "Because I cheated on them."
                sa "Oh."
                sa "...So you were with Thea too?"
                mc "Yeah."
                sa "Hah. Well, little man, you're fucked."
                mc "Come on Sander! I need some advice here."
                sa "Relax [mc], I think you're overreacting."
                sa "They won't kill you. I mean, Thea, can you imagine her hurting a fly?"
                mc "Well, that's what I thought as well."
                sa "......"
                sa "So how did they find out?"
                mc "I told them."
                sa "You... told them?"
                mc "Yeah."
                sa "You mean you weren't caught in the middle of-"
                mc "NO!"
                sa "Kid, you've have nothing to worry about. Believe me, I've been in worse situations."
                sa "The two of them probably forgave you already. You came clean, that rarely happens."
                mc "You think so...?"
                sa "Yeah."
                mc "But what about what I heard?"
                sa "What did you hear."
                mc "Something about rope and tying someone up."
                sa "Mhh... Are you sure they were talking about you?"
                mc "Uhm... I'm not really sure."
                sa "See? You got nothing to fear little man, trust me."
                mc "Alright."
                if evesex>= 1:
                        sa "Did you tell them about you and Eve?"
                        mc "Wait, y-you know that too?"
                        sa "No one's safe from the master vouyer."
                        mc "......"
                        sa "Did you tell them?"
                        mc "...I could've told them. But I didn't"
                        mc "I was afraid it would ruin Eve's reputation."
                        sa "Hmm......."
                        sa "It's not my buisness. Eve is in a very good mood nowadays, so no complaints there."
                        mc "Really?"
                        sa "Yeah. She's like a little girl who's found her first love. She's not bossing me around like a mom anymore."
                        sa "...You don't know how good that feels."
                        sa "Didn't know you were that good with the ladies, kid."
                        mc "Heh. Neither did I, honestly."
                        sa "Hahaha."
                sa "Okay kid, thats all the time I have for today."
                sa "If you're sure your harem's trying to kill you, dont worry, I'll be your back-up."
                mc "Ok... Yeah, Thanks."
                $ thcynthconfess += 1
                jump guild
        "Don't tell Sander":
                mc "I couldn't really hear anything."
                sa "Really?"
                mc "Yeah."
                sa "Bummer. Well, you haven't still mastered the art of vouyerism so you're eavesdroping skills might be too low."
                mc "Hmm... I guess so."
                sa "You should try again later."
                mc "I should."
                sa "Make sure you report your findings to me, it'll help me... Keep track of your progress."
                mc "Yeah, yeah sure."
                sa "Alright then, I'm off."
                mc "{i}Shit shit shit!"
                mc "{i}Those two are definietly going to kill me!."
                $ thcynthconfess += 1
                jump guild

label thcynth3:
hide screen hud
c "[mc]!"
mc "Y-Yes?"
c "I have something I want to tell you."
mc "......?"
c "Can you come to my room?"
mc "{i}This is suspicious."
mc "{i}Nah... I'm overreacting."
mc "What is it?"
c "Please, it's something I have to tell you in private."
mc "Fine."
"You follow Cynthia to the guild quarters."
scene cynthiaroom
show thinkmc with easeinleft
show theshy
mc "So, what is i-"
mc "Thea? what are you doing he-"
stop music
scene black with vpunch
"Something hits you in the head and you black out."
mc "Wha... Where am I."
mc "{i}Shit, can't see anything."
mc "{i}Thea! Cynthia! where are you."
c "Looks like our man's up."
mc "Cynthia?"
mc "What the hells going on!?"
mc "{i}It's obvious, they're going to kill me. I knew it."
c "It's time for your punishment."
mc "What? ...Please just take this damn thing off me."
scene cyntheakidnap with flash
mc "...Thea, what's the meaning of this?"
c "Hey, hey keep it down. We don't want to exite the neighbours."
mc "{i}Shit, shit! Should I scream?"
mc "{i}No, that will only make it quicker."
mc "{i}...I'm not sure that would really make it worse, though."
menu:
        "Try to talk them out of it":
                mc "{i}I have to talk them out of this."
                mc "Please, I'm sorry, ok? I fucked up, I get it. But please don't kill me."
        "Just accept it":
                mc "{i}This all my fault. I'm just getting what was coming for me."
                mc "I'm sorry that I failed you two. If killing me will make you happy, just get over with it."
scene cyntheakidnap2
th "...Kill you?"
c "Kill? Do you seriously think we are going to kill you?"
mc "...You weren't?"
th "We would never!"
c "Hey! We aren't {i}that{/i} messed up."
mc "I-If you're not going to kill me then... What are you...?"
c "We're going to punish you."
mc "And that involves...?"
c "We're going to fuck you."
mc "Eh? I... think I got something in my ear. Could you repeat that?"
c "We're going to screw you."
mc "{i}Huh... I thought this was supposed to be a punishment."
mc "{i}Heh... I guess they were just horny. They wanted a threesome and were too shy to ask, how cute."
mc "{i}I'll just play along-"
c "I know what you're thinking."
mc "Huh?"
c "\"That doesn't sound like a punishment, right?\""
mc "No... It sounds so bad... You know how much I hate sex..."
c "Hah, sure."
"Cynthia brings a crate of bottles and keeps it infornt of you."
mc "Wait, is that."
c "Oh yes, a crate full of my elixr. I think theres about 30 of them here."
mc "30- You mean you're going to-"
c "Oh yes."
scene cynthcrazy
c "We're going to milk you dry all night long."
mc "{i}Fuck... Fuck, this bad. They might actually kill me!"
mc "T-Thea! you didn't actualy agree to this did you, please just tell Cynthia to-"
c "It was her idea actually."
mc "WHAT!?"
th "I-It was either this or Cynthia's plan."
mc "...Which was?"
th "To... Uhm... How should i say this-"
c "Take turns fucking you in the ass."
mc "......"
mc "What the fuck!? I thought you said you weren't messed up!"
c "What? It's the only thing that came to mind."
c "But I liked Thea's idea more."
c "It helps to break the tension between us since this is how things are apparently."
c "And I also get to see you squirm."
mc "{i}Yeah, no. She's definitely messed up."
scene cyntheakidnap2
mc "Thea, I thought you said you were ok with what happened."
th "I-I..."
c "Of course she was not ok with it. Who do you think she is, some kind of angel? She's human, [mc]."
c "And when someone you love, someone who you thought you could trust, betrays you, it hurts. She just said what you wanted to hear."
mc "......"
mc "Is that true?"
th "Yes, [mc]."
mc "{i}......"
c "But we both agreed to forgive you, since you told us the truth."
c "Yet, you couldn't go unpunished."
mc "{i}sigh{/i} I'm sorry, gals... I'm glad it was you."
mc "Do what you must."
mc "{i}I'm such an asshole. Why did I feel like ths was ok?"
mc "{i}I'm... I'm so happy that they were this understanding. I'm really lucky to have these two."
mc "{i}And, hey, it could've been a worse punishment."
window hide
show cynthea movie with fade
pause
mc "Please, enough... Enough!"
c "Shut... up. We're only still three bottles down."
mc "Three!?"
mc "No more... No more...!"
show cynthea movie with fade
mc "Water... I need some water..."
pause
show cynthea movie with fade
mc "Kill me. Just kill me"
th "Ahh... Ahhh"
c "Mhh~ Ahh..."
scene theacynthbase4 with flash
c "Thea, switch. You look tired."
scene theacynthbase2
mc "No, no, Noooooooooo!"
scene theacynthbase
mc "Nooooooo"
scene theacynthsex with fade
pause
c "Ahhhh"
th "Haaaa..."
mc "..."
c "{i}Huff... Huff... Huff..."
th "{i}Huff... Huff..."
scene black with fade
"The two of them take turns fucking you. Just when you think its over Cynthia pops open a another bottle and forces it down your throat. The slight pleasure you felt at the beginning is no more as you can now barely feel anything between your legs."
"They keep ravaging your dick until nightfall."
scene thecynthsleep1 with fade
c "We're out."
th "I can't feel my legs."
c "Same here..."
th "[mc]?"
mc "......"
c "...Is he dead?"
th "[mc]!"
c "Wait, wait, don't panic!"
c "-Hey asshole! Wake up!"
mc "......"
show thecynthsleep2 with dissolve
mc "...Let me die in peace."
c "He's fine."
th "Don't scare us like that."
mc "\"Don't scare us like that?\" Whose... Whose fault is it that I'm in this state to begin with...?"
c "Yours, this is supposed to be a punishment, remember?"
mc "......"
c "Heh, you thought we'd let you off just like that, huh?"
mc "Torture isn't the first thing that comes to mind when you think of a threesome."
c "Heheh"
th "It wasn't that bad, was it?"
mc "It was, a man's not supposed to ejaculate that many times... I should've died at some point in there..."
th "Sorry."
c "Hey, we're aren't supposed to feel sorry."
th "Oh, yeah, true."
th "You... You got wh-what you deserved!"
mc "......"
mc "Thea's perfect image has been destroyed... I didn't think she could be this wild."
c "Oh, you haven't seen how wild she can be."
mc "Huh?"
th "Cynthia!"
mc "W-What do you mean?"
c "Oh, ehhh... nothing, forget I said anything."
mc "What...?"
mc "Whatever, its not like I'm in any postion to question anything."
c "Yes, exactly."
mc "......"
mc "But... I still..."
mc "I'm really sorry."
th "......"
c "......"
th "It's alright [mc], we forgive you now."
th "Right?"
c "...yeah."
mc "Thank you."
mc "{i}Everythings finally settled, I can now rest easy."
if gabetrip >= 1 or evesex >= 1 or aerinrel >= 10:
        mc "{i}...Though I still haven't told them about the others."
        mc "{i}Should I tell them?"
        c "Now thats settled, there's one more thing we wanted to know."
        c "You aren't sleeping with anyone else, right?"
        mc "......"
        menu:
                "Lie":
                        mc "No! It's only the two of you."
                        c "Hmm... Good."
                        mc "......"
                        mc "Are you guys really not mad?"
                        c "Honestly, I kind of expected it, you're too horny for compromise."
                        mc "{i}Owch."
                        c "But..."
                        c "I know you still love us."
                        c "And... ugh, I can't believe I'm being this cheesy..."
                        th "Come on, say it Cynthia."
                        c "......"
                        c "I-I can't stop loving you."
                        mc "Cynthia..."
                        mc "{i}...I'm feeling kind of bad for lying now."
                        th "After what happened these last days... I don't think it's really such a bad thing."
                        th "I feel like I got a new best friend."
                        th "And you love us all equally."
                        c "...I mean, you can pick favourites if you want."
                        th "Cynthia! No, he has to share his love equally."
                        c "Where's the fun in that?"
                        th "You just want to be his favourite don't you?"
                        c "What? I just like competition."
                        mc "......"
                        mc "You guys...I don't know what to say."
                        c "\"You're the best women a man can ask for\", that's what you want say, right?"
                        mc "......"
                        mc "Yeah."
                        show thecynthsleep3
                        mc "I love you guys."
                "Tell the truth":
                        mc "Actually..."
                        "You tell them about everything."
                        c "......"
                        th "......"
                        if gabetrip >= 1:
                            c "I knew something was up with you and the emo girl..."
                        if evesex >= 1:
                            c "Eve's always looking at you funny."
                        if aerinrel >= 10:
                            c "...But who the hell is Aerin?"
                        mc "..."
                        mc "You're not... Mad?"
                        c "Honestly, I kind of expected it, you're too horny for compromise."
                        c "But..."
                        c "I know you still love us."
                        c "And... ugh, I can't believe I'm being this cheesy..."
                        th "Come on, say it Cynthia."
                        c "......"
                        c "I-I can't stop loving you."
                        mc "Cynthia..."
                        th "After what happened these last days... I don't think it's really such a bad thing."
                        th "I feel like I got a new best friend."
                        th "And you love us all equally."
                        c "...I mean, you can pick favourites if you want."
                        th "Cynthia! No, he has to share his love equally."
                        c "Where's the fun in that?"
                        th "You just want to be his favourite don't you?"
                        c "What? I just like competition."
                        mc "......"
                        mc "You guys...I don't know what to say."
                        c "\"You're the best women a man can ask for\", that's what you want say, right?"
                        mc "......"
                        mc "Yeah."
                        mc "I love you guys."
                        show thecynthsleep3
                        th "So... since now we have to break the news to the others... Should we do it again? All together, I mean."
                        c "You mean full-on reverse gangbang? I'm in!"
                        mc "Thea! Go back to being the innocent girl, you're starting to scare me."
                        th "Hehehe."
else:
        mc "No! It's only the two of you."
        c "Hmm... Good."
        mc "......"
        mc "Are you guys really not mad?"
        c "Honestly, I kind of expected it, you're too horny for compromise."
        c "But..."
        c "I know you still love us."
        c "And... ugh, I can't believe I'm being this cheesy..."
        th "Come on, say it Cynthia."
        c "......"
        c "I-I can't stop loving you."
        mc "Cynthia..."
        th "After what happened these last days... I don't think it's really such a bad thing."
        th "I feel like I got a new best friend."
        th "And you love us all equally."
        c "...I mean, you can pick favourites if you want."
        th "Cynthia! No, he has to share his love equally."
        c "Where's the fun in that?"
        th "You just want to be his favourite don't you?"
        c "What? I just like competition."
        mc "......"
        mc "You guys...I don't know what to say."
        c "\"You're the best women a man can ask for\", that's what you want say, right?"
        mc "......"
        mc "Yeah."
        show thecynthsleep3
        mc "I love you guys."
c "{i}sigh{/i}... We should get some sleep."
c "This was one hell of a day."
th "It certainly was."
c "I'm going to put something on."
mc "Why?"
c "I don't like to sleep nude."
scene thecynthsleep5
show thecynthsleep3
"..."
"......"
c "Hey thea"
th "Mh?"
scene thecynthsleep5
c "It seems like we missed one bottle."
mc "Uh..."
scene black with fade
"......"
scene cynthiaroom with fade
mc "{i}Huff... Yawn..."
mc "Oh right... So that actually happened yesterday."
mc "They're still asleep."
mc "...Hey, guys."
mc "Wake up."
c "Hmm... Shut up."
mc "It's already mor- ...Wait, it's already noon!"
c "Mhn... Just go on without us."
c "We'll hold them off..."
mc "What?"
c "{i}Snore..."
mc "Thea."
th "......"
mc "They're both out cold."
mc "...Guess I'll just leave."
"You get up, wash your face and put on your clothes."
mc "I'm going down stairs."
"Thea and cynthia" "......"
"You head downstairs."
scene adgc1 with fade
j "Oh hello, [mc]. Were you visiting someone?"
mc "Y-Yeah."
j "Hmm... I didn't see you come in."
mc "Really? Haha I just came in."
j "Huh."
j "Anyway, is anything wrong with Thea? She didn't come in."
mc "Thea, yeah she's....a bit sick."
j "Goodness, I hope it isn't anything serious."
mc "Oh no, no, It's just a small cough."
j "That's a relief."
mc "See you later then."
j "Alright, [mc]. Take care."
scene agblr
mc "{i}Dogded an arrow there."
mc "......"
mc "{i}I still can't belive last night actually happened."
mc "{i}If I knew it was going to end up like this I wouldn't have been so paranoid"
$ thcynthconfess += 1
jump guild
