init python:
    def galleryUnlock():
        persistent.pt1End = True
        persistent.sneakyMegan = True
        persistent.trissFlash = True
        persistent.trissStare = True
        persistent.acidTrip = True
        persistent.Taliya6dom = True
        persistent.Taliya6 = True
        persistent.Taliya5 = True
        persistent.Taliya4 = True
        persistent.Taliya3 = True
        persistent.Taliya2 = True
        persistent.Taliya1 = True
        persistent.zenGoodEnd = True
        persistent.zenTroll = True
        persistent.zenDirewolf = True
        persistent.zenHeal = True
        persistent.zenPeek = True
        persistent.zenPeek2 = True
        persistent.zenRepaired = True
        persistent.zenMurders = True
        persistent.introZen = True
        persistent.helpAerin = True
        persistent.aerinSex = True
        persistent.aerinLickies = True
        persistent.aerinKiss = True
        persistent.aerinTea = True
        persistent.sexNessa = True
        persistent.nessaBlowjob = True
        persistent.nessaPantyless = True
        persistent.zenelithRape = True
        persistent.zenelithDefeated = True
        persistent.aerinDead = True
        persistent.priestShow = True
        persistent.millyEve = True
        persistent.followedEve = True
        persistent.theaFirstTime = True
        persistent.theaNakedSleep = True
        persistent.theaGrave = 2
        persistent.theaRape = True
        persistent.cynthFirstTime = True
        persistent.cynthStrip = True
        persistent.ears = True
        persistent.cynthVampire = True
        persistent.cynthWatchingOver = True
        persistent.savedCynthBandit = True
        persistent.cynthMCFight = True
        persistent.cynthFireplace = True
        persistent.direWolf = True
        persistent.cynthiaTraining = True
        persistent.cynthiaFirstDate = True
        persistent.globDeath = True
        persistent.cynthiaTent = True
        persistent.cynthCovers = True
        persistent.abandonCynthia = True
        persistent.goblinBarrel = True
        persistent.taliyaGoblins = True
        persistent.gabeMissionary = True
        persistent.gabeDoggy = True
        persistent.gabePicnic = True
        persistent.gabeHandjob = True
        persistent.gabeDildo = True
        persistent.gabeFingering = True
        persistent.gabeSleep = True
        persistent.testDone = True
        persistent.yakina = True
        persistent.scenery = True
        persistent.eveBath = True
        persistent.bronzeParty = True
        persistent.peteStargazing = True
        persistent.studying = True
        persistent.nadiaLick = True
        persistent.nadiaBlowjob = True
        persistent.peekingTime = True
        persistent.stareCynthia = True
        persistent.scarLocker = True
        persistent.theaBed = True
        persistent.theaCleaning = True
        persistent.theaGabe1 = True
        persistent.Taliya6fem = True
        return


label galleryUnlock:
        $ persistent.pt1End = True
        $ persistent.sneakyMegan = True
        $ persistent.trissFlash = True
        $ persistent.trissStare = True
        $ persistent.acidTrip = True
        $ persistent.Taliya6dom = True
        $ persistent.Taliya6 = True
        $ persistent.Taliya5 = True
        $ persistent.Taliya4 = True
        $ persistent.Taliya3 = True
        $ persistent.Taliya2 = True
        $ persistent.Taliya1 = True
        $ persistent.zenGoodEnd = True
        $ persistent.zenTroll = True
        $ persistent.zenDirewolf = True
        $ persistent.zenHeal = True
        $ persistent.zenPeek = True
        $ persistent.zenPeek2 = True
        $ persistent.zenRepaired = True
        $ persistent.zenMurders = True
        $ persistent.introZen = True
        $ persistent.helpAerin = True
        $ persistent.aerinSex = True
        $ persistent.aerinLickies = True
        $ persistent.aerinKiss = True
        $ persistent.aerinTea = True
        $ persistent.sexNessa = True
        $ persistent.nessaBlowjob = True
        $ persistent.nessaPantyless = True
        $ persistent.zenelithRape = True
        $ persistent.zenelithDefeated = True
        $ persistent.aerinDead = True
        $ persistent.priestShow = True
        $ persistent.millyEve = True
        $ persistent.followedEve = True
        $ persistent.theaFirstTime = True
        $ persistent.theaNakedSleep = True
        $ persistent.theaGrave = 2
        $ persistent.theaRape = True
        $ persistent.cynthFirstTime = True
        $ persistent.cynthStrip = True
        $ persistent.ears = True
        $ persistent.cynthVampire = True
        $ persistent.cynthWatchingOver = True
        $ persistent.savedCynthBandit = True
        $ persistent.cynthMCFight = True
        $ persistent.cynthFireplace = True
        $ persistent.direWolf = True
        $ persistent.cynthiaTraining = True
        $ persistent.cynthiaFirstDate = True
        $ persistent.globDeath = True
        $ persistent.cynthiaTent = True
        $ persistent.cynthCovers = True
        $ persistent.abandonCynthia = True
        $ persistent.goblinBarrel = True
        $ persistent.taliyaGoblins = True
        $ persistent.gabeMissionary = True
        $ persistent.gabeDoggy = True
        $ persistent.gabePicnic = True
        $ persistent.gabeHandjob = True
        $ persistent.gabeDildo = True
        $ persistent.gabeFingering = True
        $ persistent.gabeSleep = True
        $ persistent.testDone = True
        $ persistent.yakina = True
        $ persistent.scenery = True
        $ persistent.eveBath = True
        $ persistent.bronzeParty = True
        $ persistent.peteStargazing = True
        $ persistent.studying = True
        $ persistent.nadiaLick = True
        $ persistent.nadiaBlowjob = True
        $ persistent.peekingTime = True
        $ persistent.stareCynthia = True
        $ persistent.scarLocker = True
        $ persistent.theaBed = True
        $ persistent.theaCleaning = True
        $ persistent.theaGabe1 = True
        $ persistent.Taliya6fem = True
        return
