define flash  =  Fade(0.1, 0.0, 0.5, color="#fff")
define u = Character("Uncle Pete", color = "#e6ccb3")
define g = Character("Gabrial", color = "#DB93FF")
define s = Character("Scarlet", color = "#EFC667")
define b = Character("Boris", color = "#D8CBBE")
define t = Character("Taliya", color = "#DD8E8B")
define e = Character("Evelyn", color = "#B6E268", image = "eve")
define sa = Character("Sander", color = "#FFD747", image = "sander")
define j = Character("July", color = "#FFB575")
define l = Character("Lori", color = "#8C79C6")
define me = Character("Mervin", color = "#B39CD8")
define c = Character("Cynthia", color = "#FF7F7F")
define m = Character("Megan", color = "#BDA9C6")
define tr = Character("Triss", color = "#FFDAC1")
define th = Character("Thea", color = "#FF893A")
define n = Character("Nessa", color = "#8DE549")
define mi = Character("Milly", color = "#FFFA00")
define a = Character("Aerin", color = "#47E847")
define zn = Character("Zenelith", color = "#A4E53B")
define znr = Character("Zenelith", color = "#A4E53B", image = "znrag")
define znd = Character("Zenelith", color = "#A4E53B", image = "zndress")
define zns = Character("Zenelith", color = "#A4E53B", image = "znstaff")
define le = Character("Leshek", color = "#e6ccb3")
define he = Character("You", color = "#96C7FF")
define y = Character("Yakina", color = "#C64745")
define Nadia = Character("Nadia", color = "#C16641")
define morg = Character("Morgan", color = "#47E847")
define tw = Character("Twig", color = "#fff")
define mal = Character("Malek", color = "#A552A8")
default mcn = "Your name"
define mc = Character("[mcn]", image="prot")
